// frontend/src/utils/downloadPDF.js

import html2pdf from 'html2pdf.js';
import languageList from './languageList';

const formatFilenameTimestamp = () => {
  const now = new Date();
  return now.toISOString().replace(/[-:.]/g, '_');
};

const getLanguageLabel = (code) => {
  const found = languageList.find((lang) => lang.code === code);
  return found ? found.label : code;
};

export const downloadAsPDF = (
  inputText,
  outputText,
  label = 'output',
  options = {}
) => {
  const now = new Date();
  const formattedDate = now.toLocaleString();
  const fromLang = getLanguageLabel(options.inputLanguage);
  const toLang = getLanguageLabel(options.outputLanguage);
  const username = options.username || 'User';

  // Create a hidden container
  const container = document.createElement('div');
  container.style.fontFamily = 'Noto Sans, sans-serif';
  container.style.padding = '20px';
  container.style.width = '210mm';
  container.style.maxWidth = '210mm';
  container.style.boxSizing = 'border-box';

  // Set the content
  container.innerHTML = `
    <h2 style="text-align: center; margin-bottom: 10px;">${label.toUpperCase()}</h2>
    <div style="font-size: 15px; margin-bottom: 10px;">
      ${
        label === 'translation'
          ? ` 
            <div><strong>Source:</strong> ${fromLang}</div>
            <div><strong>Translated To:</strong> ${toLang}</div>
          `
          : ` 
            <div><strong>Type:</strong> ${options.summaryType || 'N/A'}</div>
            <div><strong>Length:</strong> ${options.summaryLength || 'N/A'}</div>
          `
      }
      <div><strong>Date:</strong> ${formattedDate}</div>
    </div>
    <hr />
    <h3 style="margin-top: 10px;">Input:</h3>
    <div style="white-space: pre-wrap; font-size: 16px; margin-bottom: 15px;">${inputText || 'N/A'}</div>
    <h3>Output:</h3>
    <div style="white-space: pre-wrap; font-size: 16px;">${outputText || 'N/A'}</div>
    <hr style="margin-top: 20px;" />
    <div style="display: flex; justify-content: space-between; font-style: italic; font-size: 14px;">
      <div>Generated By <strong>MY-NLP-APP 🤖</strong></div>
      <div>Created by <strong>${username} 🧑‍💻</strong></div>
    </div>
  `;

  document.body.appendChild(container);

  // Convert to PDF
  html2pdf()
    .set({
      margin: 0.5,
      filename: `${label.toUpperCase()}_${formatFilenameTimestamp()}.pdf`,
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    })
    .from(container)
    .save()
    .then(() => {
      document.body.removeChild(container);
    });
};
